# Generated by Django 6.0.6 on 2026-07-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
